build_serial:
	g++ serial.cpp -o serial -Wall

build_optim:
	g++ serial_optim.cpp -o serial_optim -Wall

build_paralel:
	g++ paralel.cpp -o paralel -Wall -fopenmp

clean:
	rm -f serial serial_optim paralel